version: "2"

services:
  nginx-web:
    image: nginx:alpine
    container_name: nginx-web
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - htpasswd:/etc/nginx/htpasswd
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "10"

#  nginx-letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    container_name: nginx-letsencrypt
#    restart: always
#    volumes:
#      - conf:/etc/nginx/conf.d
#      - vhost:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#      - certs:/etc/nginx/certs:rw
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
#      NGINX_PROXY_CONTAINER: nginx-web
#    logging:
#      driver: json-file
#      options:
#        max-size: "2m"
#        max-file: "10"

  le-godaddy-dns:
    image: "uschti/le-godaddy-dns"
    environment:
      GD_KEY: dL3hLo9tEefn_sZaZ823pbGAvB5PiMLAGM
      GD_SECRET: GTq4yzPtSxYmnXrX9XhVpT
    volumes:
      - certs:/data/certs
      - certs:/data/keys
      - ./proxy/renew_certificates.conf:/data/letsencrypt/renew_certificates.conf
      - cert-data:/data/letsencrypt/dehydrated/certs

volumes:
  conf:
  vhost:
  html:
  certs:
  htpasswd:
  cert-data:
networks:
  default:
    external:
      name: webproxy
